### ISSUE TITLE
Pipe query outputs to filter subsequent queries

### ISSUE THREAD

**Issue by j-schreiber** [j-schreiber/js-sf-cli-plugin#14]
## Problem Description
- Most query-chains are normalisation of subselect queries (all contacts from accounts, where ...)
- Currently, users have to duplicate the same query filter through lookup on the child object

```yaml
- objectName: Account
    query:
      fetchAllFields: true
      filter: ClientProfile__r.MetadataRecord__c = 'TMH_US_LLC'
  - objectName: AccountTeamMember
    query:
      fetchAllFields: true
      filter: Account.ClientProfile__r.MetadataRecord__c = 'TMH_US_LLC'
  - objectName: Contact
    query:
      fetchAllFields: true
      filter: Account.ClientProfile__r.MetadataRecord__c = 'TMH_US_LLC'
```
- If the filter changes (due to refinement), multiple queries need to be updated
- If the parent filter is more complex (e.g. includes a subselect filter), it may become impossible (or at least: unreadable)

## Solution Design
- Convenient export of the the "id field" of the parent query
```yaml
- objectName: Account
    query:
      fetchAllFields: true
      filter: ClientProfile__r.MetadataRecord__c = 'TMH_US_LLC'
    exportIdsAs: myAccountIds
  - objectName: Contact
    queryString: SELECT Id,Email FROM Contact
    parent:
      field: AccountId
      bind: myAccountIds
```

### Implementation Ideas
Consider example that should resolve to `SELECT ... FROM Contact WHERE AccountId IN :myAccountIds`

During validation:
- When engine detects a variable bind, it automatically validates that variable is exported **before** it is used
- Id types match (e.g. lookup field that is specified in the bind points to `Account`, and variable is exported by `Account` query)
- Only a single parent bind-variable is supported (explicitly stating the lookup field, because a child may have multiple lookups to the same parent object)

During record retrieval
- If bind is detected, the bind variable is dynamically resolved to `AccountId IN (...)` query string (resolving relationship between parent/child dynamically using describe).
- This can be combined with explicit queries or query-files. The filter is dynamically resolved to `Field IN (...)` and added with `AND` operator.
- Load all account record ids (e.g. from `exports/.../Account/*.json` or because they were already exported by account retrieval step) to memory (for now, we do not optimize for memory consumption, because this will only be relevant if we have millions of parent records). Options to monitor memory usage: [stackoverflow](https://stackoverflow.com/questions/20018588/how-to-monitor-the-memory-usage-of-node-js)
- Chunk parent record ids in small sizes (500; the query-string-limit should be around 800 ids, according to salesforce docs).
- Iterate through each chunk with the standard retrieve loop (including query-more) (i.e. nested loops)
- The spinner status should include information about the parent-id chunk AND the record retrieve chunk, to get sense of overall progression. It is not possible to determine the number of sub-requests per parent-id chunk in advance (a single parent can contain 1 child or 1000s of children.

## Considerations
- If parent object id is exported, the engine needs to make smart optimisations to batch child records
- If parent object has 10s of thousands of records, and child object a multitude of that, we would run in string / buffer overflow
