### ISSUE TITLE
"Limit" property in query object for plan exports

### ISSUE THREAD

**Issue by j-schreiber** [j-schreiber/js-sf-cli-plugin#23]
## Problem Description
- We do not want to write our own query file to quickly test exports by only limiting results to 10
- The `filter` property only creates a `WHERE` clause

## Solution Design

Something like this would be sufficient

```yaml
- objectName: Account
  query:
    fetchAllFields: true
    limit: 10
```
